### ISSUE TITLE
Test Issue

### ISSUE THREAD

**Issue by Freya46** [ProEnduro/SVISS_ZES#4]
This is a test issue which for the false medical leave calculation.
(Works already in the commit of today -> gonna make a new test commit to resolve this issue later)

**Comment by ProEnduro** [comment]
Laft

Am 12.02.2018 12:37 schrieb "Sebastian Neumeister" <notifications@github.com

**Comment by Freya46** [comment]
hast du grad ne email notification davon bekommen?^^

**Comment by ProEnduro** [comment]
Jo. Des passt schon so, dann Howi wos zum lesen bam Heer xd

Am 12.02.2018 12:45 schrieb "Sebastian Neumeister" <notifications@github.com
